---
title: "Seed Bank Test"
output:
  html_document:
    df_print: paged
editor_options:
  code_folding: hide
  chunk_output_type: inline
---

```{r, message=FALSE}
library(here)
library(tidyverse)
library(cowplot)
library(scales)
library(ggrepel)
```

Read data
```{r}
d <- read_csv(here("data", "seed-bank", "seed_bank_test.csv"))

d <- d %>% 
  rename(manipulated = long) %>% 
  rename(simple = short)
```
Naive expectation
```{r}
dilute <- function (initial, len, dilution){
  x <- c(initial, rep(NA, len-1))

  for(i in 2:len){
    x[i] <- x[i-1]*dilution
    
  }
    return(x)
}



d.exp <- tibble(day = 0:12,
                manipulated = dilute(initial = d$manipulated[1],
                                    len = 13, dilution = 0.2),
                simple = dilute(initial = d$simple[1],
                                len = 13, dilution = 0.01))%>%
   pivot_longer(-day, names_to = "trt", values_to = "cfu.ml")


lab.exp <- 
  d.exp %>% 
  filter(day == 3 | day==4 ) %>%
  group_by(trt)%>%
  summarise(cfu.ml = mean(cfu.ml), day = mean (day)) %>% 
  mutate(day = day +.5) %>%
  mutate(lab = if_else(trt == "manipulated", "1:5", "1:100"))

```
Deviation from expectation
```{r}
dj <- d%>%
  pivot_longer(-day, names_to = "trt", values_to = "cfu.ml") %>% 
  left_join(.,d.exp, by = c("day","trt"))
```



```{r}
#plot
d%>%
  pivot_longer(-day, names_to = "trt", values_to = "cfu.ml") %>% 
    #adjust treatment name
  mutate(trt = if_else(trt == "manipulated", "+external seed bank", "-external seed bank") %>% fct_rev()) %>% 
  ggplot(aes(x = day, y = cfu.ml))+
  geom_line(data = d.exp, aes(group = trt), linetype = 2, linewidth = 1, show.legend = F, color="grey70")+
  geom_segment(data = dj, aes(x = day, xend = day,
                              y = cfu.ml.x, yend = cfu.ml.y),color="grey70")+
  geom_text(data = lab.exp, aes(label = lab), color="grey70")+
  geom_point(aes(shape=trt, fill= trt), size = 3)+
  theme_classic(base_size = 15)+
  panel_border(color = "black", size = 1.5)+
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  coord_cartesian(ylim = c(10,NA))+
  scale_x_continuous(breaks = seq(0, 12, 1))+
  scale_shape_manual(values = c(22,21)
                     # labels = c("long seed bank", "short seed bank")
                     )+
  scale_color_manual(values = c("black","black"))+
  scale_fill_manual(values = c("black","white") 
                    # labels = c("long seed bank", "short seed bank")
                    )+

      theme(legend.position = c(.7, .85),
            legend.title = element_blank(),
            strip.background = element_blank(),
            strip.text = element_text(face = "bold"))+
  ylab("Cm-resistant CFU (per mL)")+
  xlab("Time (day)")+
  annotation_logticks(sides = "l")
  
ggsave(here("plots","seed-bank-test.png"), width = 5, height = 4)
```

